#Initial commit
name: Hello World Workflow
on: [push]

jobs:
    run-script:
        runs-on: ubuntu-latest
        steps:
            - name: helloworld
              run: echo "Hello World"
            - name: multi line command
              run: |
                  echo "This is line 1"
                  echo "This is line 2"
                  echo "This is line 3"
                  echo "This is line 4"
                  echo "This is line 5"
