name: Dependand and parallel jobs
on:
    push:
        branches:
            - main

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: First step
              run: echo "This is the first job"
    parallel-job:
        runs-on: ubuntu-latest
        steps:
            - name: parallel job
              run: cat /etc/os-release
    dependent-job:
        needs: first-job
        runs-on: windows-latest
        steps:
            - name: dependent job
              run: winver
